# -*- coding: utf-8 -*-
"""Smali_opcode_extraction

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Z_aOOrJxb0NCqMq_v0A8s7memIcZ-iD

## ***Opcode Extraction from smali file and counting frquency of occurences ***
"""

from glob import glob
import os
import csv
from re import split


"""Write the name of the file csv file in which you want to save the out of the code (eg. benign.csv). then press enter"""

csvn = input("Csv to be updated? ")
  
csvf = open(csvn, 'w') 

csvwriter = csv.writer(csvf)

file_types = ('/DATA/home/AbhishekAnand/Drebin/drebin-5-smali/*.smali', '/DATA/home/AbhishekAnand/Drebin/drebin-5-smali/*.txt')

flag = 1


for file_type in file_types:
    text_files = glob(file_type)
    print(text_files)

    for file_name in text_files:
        with open(file_name) as data_file:
            check = [".","#","*",";"]
            data_line = data_file.readlines()
#           print(data_line)
            reduced_data = []
            for line in data_line:
                line = line.lstrip()
                if len(line) and line[0] not in check:
                    extracted_word = split("/| |\n", line)
                    reduced_data.append(extracted_word[0])
#           print(reduced_data)
            with open("/DATA/home/AbhishekAnand/Drebin/keys.txt") as dalvik_opcodes:
                dalvik_line = dalvik_opcodes.readlines()
                row = [os.path.splitext(os.path.basename(file_name))[0], os.path.splitext(os.path.basename(file_name))[1]]
                header = ["File Name", "File Type"]
                for line in dalvik_line:
                    header.append(line.split("\n")[0])
                    row.append(reduced_data.count(line.split("\n")[0]))
#                   print(row)
                if flag == 1:
                    csvwriter.writerow(header)
                    flag = 0
            csvwriter.writerow(row)
csvf.close()



